### ISSUE TITLE
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzServiceBusNamespace' :

### ISSUE THREAD

**Issue by PartTimeLegend** [itoleck/AzureSaveMoney#27]
Command: Get-AzSMAllResources -Subscription <redacted>

Expected behaviour: To run completely.

Error output:

- The output type 'Microsoft.Azure.Commands.ServiceBus.Models.PSNamespaceAttributes' is changing
- The following properties in the output type are being deprecated : 'ResourceGroup'
- The following properties are being added to the output type : 'ResourceGroupName'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.

**Comment by itoleck** [comment]
Cannot reproduce in latest build, 1.0.17.
