### ISSUE TITLE
TenantId value required when exec Get-AzSMAllResources

### ISSUE THREAD

**Issue by PartTimeLegend** [itoleck/AzureSaveMoney#28]
Command: Get-AzSMAllResources -Subscription <redacted>

Expected behaviour: Command to run successfully without further prompts.

Output: 
cmdlet Get-AzSMAllResources at command pipeline position 1
Supply values for the following parameters:
TenantID:

**Comment by itoleck** [comment]
A valid TenantID is required to run the command. 

Get-Help Get-AzSMAllResources -full
-TenantID <String>
        Azure tenant ID in the format, 00000000-0000-0000-0000-000000000000
        Required?                    true

**Comment by PartTimeLegend** [comment]
The readme in the repo doesn't show the need for tenant.
