### ISSUE TITLE
Add option to print output as JSON/CSV

### ISSUE THREAD

**Issue by Zenidd** [itoleck/AzureSaveMoney#33]
Hello @itoleck, how is it going?

Your project its been helpful for me, thanks for putting effort into this. I think Azure should have a bundled tool with this purpose.

Anyway, I think something really cool to have could be a JSON/CSV output option to easily get the output into an Excel spreadsheet.

Greetings,
-Zenidd

**Comment by itoleck** [comment]
You can do this with any output that supports objects. Should work with all cmdlets besides Get-AzsmAllResources.

i.e.
Get-AzSMUnusedDisks -SubscriptionID 00000000-0000-0000-0000-000000000000 |ConvertTo-Json

**Comment by itoleck** [comment]
Closing after guidance
