### ISSUE TITLE
Get-AzSMVMsNotDeletedAfterImage drops error if SourceVirtualMachine is null

### ISSUE THREAD

**Issue by klem-ent** [itoleck/AzureSaveMoney#34]
Hello,

the Get-AzSMVMsNotDeletedAfterImage function is firing the following error if the "SourceVirtualMachine" field is null on an Azure image:

`Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.`

I'm actually working around this error with a try catch in my script, but maybe it could be handled directly within the function?

**Comment by itoleck** [comment]
Hello klem-ent, how does your image resource end up without a source VM id? Was the image uploaded from Hyper-V?

**Comment by klem-ent** [comment]
Hello Itoleck,
I don't remember, but yeah that was probably the case. 
The disks have been deleted now so I cannot recreate the error.

Edit:
After some investigation, it looks like the image resource was created manually and based on a custom VHD file. I don't know if it's normal, but each time I'm creating an image based on a custom VHD it end with a blanck "source virtual machine" field.
