### ISSUE TITLE
Issue Connect-AzureAD -TenantId $TenantID > Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly      | 'System.Core, Version 4.0.0.0

### ISSUE THREAD

**Issue by janvanuytrecht** [itoleck/AzureSaveMoney#38]
Hi, 

When I run the script I get the following error:
35 |        $null = Connect-AzureAD -TenantId $TenantID
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly
     | 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type
     | 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral,
     | PublicKeyToken=b77a5c561934e089'.

What could be the reason?
Just be sur I checked that I am owner on the sub, and the tenantId is correct.

I am running the cmdlet via PS7 on Windows 11.

**Comment by itoleck** [comment]
Sounds like you were missing a .net runtime. Use my winget commands in gist to install .net runtimes. https://gist.github.com/itoleck/9687502b2ef957584f3661be195bc4c3
